# -*- coding: utf-8 -*-
"""multiAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOIf_TNYrBE3dfgWFqUYvMFlnzU66Ygt
"""

# !pip install scikit-learn pandas

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression



"""**load all files**"""

# Update paths if needed
df = pd.read_csv("dataset.csv")
desc = pd.read_csv("symptom_Description.csv")
prec = pd.read_csv("symptom_precaution.csv")
sev = pd.read_csv("Symptom-severity.csv")

"""**preprocess the main dataset**"""

def combine_symptoms(row):
    symptoms = []
    for col in df.columns[1:]:  # skip Disease column
        if pd.notna(row[col]):
            symptoms.append(str(row[col]))
    return " ".join(symptoms)

df["text"] = df.apply(combine_symptoms, axis=1)

df = df[["text", "Disease"]]
df.rename(columns={"Disease": "disease"}, inplace=True)

# Encode labels
le = LabelEncoder()
df["label"] = le.fit_transform(df["disease"])

print(df.head())

"""**TF-IDF Vectorization**"""

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["text"])
y = df["label"]

"""**Train model**"""

clf = LogisticRegression(max_iter=1000)
clf.fit(X, y)



############# not Noww

# X = [bert_encode(text)[0] for text in df["text"]]
# y = df["label"]



"""**Building agents**

**description agent**
"""

def get_description(disease):
    row = desc[desc["Disease"] == disease]
    if not row.empty:
        return row["Description"].values[0]
    return "No description available"

"""**Precuation Agent**"""

def get_precautions(disease):
    row = prec[prec["Disease"] == disease]
    if not row.empty:
        return row.values[0][1:]
    return []

"""**Severity Agent**"""

severity_dict = dict(zip(sev["Symptom"], sev["weight"]))

def calculate_severity(symptoms):
    score = sum([severity_dict.get(s, 0) for s in symptoms])

    if score > 15:
        return "HIGH RISK ⚠️"
    elif score > 5:
        return "MEDIUM RISK"
    return "LOW RISK"



"""**NLP+ Multi Agent**

**Symptom Extrator**
"""

SYMPTOMS = [s.strip() for s in sev["Symptom"].values]

# def extract_symptoms(text):
#     text = text.lower()
#     matched = []
#     for s in SYMPTOMS:
#         readable = s.replace("_", " ").lower()  # "high_fever" → "high fever"
#         if readable in text:
#             matched.append(s)
#     return matched
def extract_symptoms(text):
    text = text.lower()
    matched = []
    for s in SYMPTOMS:
        readable = s.replace("_", " ").lower()  # "high_fever" → "high fever"
        if readable in text:
            matched.append(s)
    return matched
"""**Intent Router**"""

def intent_router(text):
    if "chest pain" in text or "breathing" in text:
        return "emergency"
    return "normal"

"""**Emergenncy agentt**"""

def emergency_agent():
    return "⚠️ Emergency detected. Seek immediate medical help."

"""**Disease Prediction Agent**"""

def predict_disease(text):
    vec = vectorizer.transform([text])
    probs = clf.predict_proba(vec)[0]

    top_indices = probs.argsort()[-3:][::-1]

    results = []
    for idx in top_indices:
        disease = le.inverse_transform([idx])[0]
        results.append((disease, probs[idx]))

    return results

"""**Response Agent**"""
def response_generator(text):
    intent = intent_router(text)
    normalized = normalize_input(text)       # normalize once here
    symptoms = extract_symptoms(normalized)  # ← normalized text ✅
    diseases = predict_disease(normalized)
# def response_generator(text):
#     intent = intent_router(text)

#     if intent == "emergency":
#         return emergency_agent()

#     symptoms = extract_symptoms(text)
#     diseases = predict_disease(text)
    risk = calculate_severity(symptoms)

    top_disease = diseases[0][0]
    description = get_description(top_disease)
    precautions = get_precautions(top_disease)

    response = f"""
🧠 Symptoms Detected: {symptoms}

  

🤖 Possible Conditions:
"""

    for d, p in diseases:
        response += f"\n- {d} ({int(p*100)}%)"

    response += f"\n\n📖 Description:\n{description}"

    response += f"\n\n⚠️ Precautions:"
    for p in precautions:
        response += f"\n- {p}"

    response += f"\n\n🚨 Risk Level: {risk}"
    response += "\n\n⚠️ This is not a medical diagnosis."

    return response

SYMPTOM_SYNONYMS = {
    "high_fever":           ["fever", "high temperature", "burning up", "feeling hot", "high fever"],
    "mild_fever":           ["mild fever", "low grade fever", "slight fever"],
    "fatigue":              ["tired", "low energy", "exhausted", "fatigue", "weakness"],
    "headache":             ["head hurts", "migraine", "head pain", "headache"],
    "cough":                ["coughing", "cough"],
    "chest_pain":           ["chest pain", "chest discomfort"],
    "nausea":               ["nausea", "feeling sick", "vomiting"],
    "breathlessness":       ["breathing difficulty", "shortness of breath", "can't breathe"],
    "chills":               ["chills", "shivering", "feeling cold"],
    "sweating":             ["sweating", "sweaty", "night sweats"],
    "loss_of_appetite":     ["no appetite", "not hungry", "loss of appetite"],
    "muscle_weakness":      ["muscle weakness", "weak muscles"],
    "back_pain":            ["back pain", "backache"],
    "abdominal_pain":       ["stomach pain", "abdominal pain", "stomach ache", "belly pain"],
}

def normalize_input(text):
    text = text.lower()
    normalized = []
    for symptom, synonyms in SYMPTOM_SYNONYMS.items():
        for phrase in synonyms:
            if phrase in text:
                normalized.append(symptom)  # adds "high_fever" — matches training data!
    normalized.append(text)
    return " ".join(normalized)

"""**Final Agent Pipeline**"""

# def multi_agent_chatbot(user_input):
#     normalized_text = normalize_input(user_input)   # 🧠 BERT layer
#     return response_generator(normalized_text)
def multi_agent_chatbot(user_input):
    return response_generator(user_input)


# """Testtttttttttttttttt"""

print(multi_agent_chatbot("I have fever, headache and fatigue"))

